# Generated by Django 3.0.6 on 2022-05-18 20:49

import asignacion.models
import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catastro_equipos', '__first__'),
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignationState',
            fields=[
                ('id_asig_status', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID Estado Asignación')),
                ('asignation_status', models.CharField(choices=[('Asignado', 'Asignado'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Dañado', 'Dañado')], max_length=10, verbose_name='Estado de Asignacion')),
            ],
            options={
                'verbose_name': 'Estado de Asignacion',
                'verbose_name_plural': 'Estado de Asignaciones',
                'db_table': 'EstadoAsignacion',
                'ordering': ['id_asig_status'],
            },
        ),
        migrations.CreateModel(
            name='AsignationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asig_id', models.IntegerField(verbose_name='ID de Asignacion')),
                ('date_init', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Entrega')),
                ('date_fin', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Retiro')),
                ('observation', ckeditor.fields.RichTextField(verbose_name='Observación')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catastro_equipos.Product', verbose_name='Producto Asignado')),
                ('product_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catastro_equipos.ProductStatus', verbose_name='Estado de Producto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.User', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'db_table': 'Historial',
                'ordering': ['-asig_id'],
            },
        ),
        migrations.CreateModel(
            name='Asignation',
            fields=[
                ('asig_id', models.IntegerField(default=asignacion.models.random_id, primary_key=True, serialize=False, unique=True, verbose_name='ID de Asignación')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Asignación')),
                ('dp_boss', models.CharField(choices=[('Directora de Proyecto', 'Directora de Proyecto'), ('Jefe de Auditoria y Control Interno', 'Jefe de Auditoria y Control Interno'), ('Coordinador Académico', 'Coordinador Académico'), ('Director(a) de Proyecto', 'Director(a) de Proyecto'), ('Jefe de Coordinación Académica', 'Jefe de Coordinación Académica'), ('Key Account Manager', 'Key Account Manager'), ('Encargado de Logística y Control de Stock', 'Encargado de Logística y Control de Stock'), ('Lider Técnico', 'Lider Técnico'), ('Diseñador Multimedia y Jefe Técnico', 'Diseñador Multimedia y Jefe Técnico'), ('Office Manager - Comunicaciones Internas y Jefa de coordinación académica', 'Office Manager - Comunicaciones Internas y Jefa de coordinación académica'), ('Gerente General', 'Gerente General'), ('Jefe de Capacitación y Desarrollo Organizacional', 'Jefe de Capacitación y Desarrollo Organizacional'), ('Directora de Proyecto Junior', 'Directora de Proyecto Junior'), ('Gerente de Capacitación', 'Gerente de Capacitación'), ('Gerente Comercial', 'Gerente Comercial'), ('Subgerenta de Proyectos', 'Subgerenta de Proyectos'), ('Gerente de Marketing y Comunicaciones', 'Gerente de Marketing y Comunicaciones'), ('Subgerente TI', 'Subgerente TI')], default='Seleccione un Departamento', max_length=100, verbose_name='Departamento a Cargo')),
                ('boss', models.CharField(max_length=100, validators=[asignacion.models.validate_boss], verbose_name='Autorizado por (Jefe)')),
                ('acta_ent', ckeditor.fields.RichTextField(verbose_name='Acta de entrega')),
                ('id_asig_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.AsignationState', verbose_name='ID Estado Asignación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro_equipos.Product', verbose_name='Producto Asignado')),
                ('product_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro_equipos.ProductStatus', verbose_name='Estado de Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.User', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Equipo Asignado',
                'verbose_name_plural': 'Equipos Asignados',
                'db_table': 'EquiposAsignados',
                'ordering': ['-date', 'product', 'user'],
            },
        ),
    ]
