# Generated by Django 4.0.1 on 2022-06-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0002_alter_asignationhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignation',
            name='dp_boss',
            field=models.CharField(choices=[('Directora de Proyecto', 'Directora de Proyecto'), ('Jefe de Auditoria y Control Interno', 'Jefe de Auditoria y Control Interno'), ('Coordinador Académico', 'Coordinador Académico'), ('Director(a) de Proyecto', 'Director(a) de Proyecto'), ('Jefe de Coordinación Académica', 'Jefe de Coordinación Académica'), ('Key Account Manager', 'Key Account Manager'), ('Encargado de Logística y Control de Stock', 'Encargado de Logística y Control de Stock'), ('Lider Técnico', 'Lider Técnico'), ('Diseñador Multimedia y Jefe Técnico', 'Diseñador Multimedia y Jefe Técnico'), ('Office Manager - Comunicaciones Internas y Jefa de coordinación académica', 'Office Manager - Comunicaciones Internas y Jefa de coordinación académica'), ('Gerente General', 'Gerente General'), ('Jefe de Capacitación y Desarrollo Organizacional', 'Jefe de Capacitación y Desarrollo Organizacional'), ('Directora de Proyecto Junior', 'Directora de Proyecto Junior'), ('Gerente de Capacitación', 'Gerente de Capacitación'), ('Gerente Comercial', 'Gerente Comercial'), ('Subgerenta de Proyectos', 'Subgerenta de Proyectos'), ('Gerente de Marketing y Comunicaciones', 'Gerente de Marketing y Comunicaciones'), ('Subgerente TI', 'Subgerente TI'), ('Seguridad de la Información', 'Seguridad de la Información')], default='Seleccione un Departamento', max_length=100, verbose_name='Departamento a Cargo'),
        ),
    ]
