# Generated by Django 4.0.1 on 2022-08-03 17:17

import datetime
from django.db import migrations, models
import phone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID Estado de Producto')),
                ('phone_type', models.CharField(choices=[('TABLET', 'TABLET'), ('CELULAR', 'CELULAR')], default='', max_length=20, verbose_name='Tipo de Producto')),
                ('phone_name', models.CharField(choices=[('NK', 'NOKIA'), ('SM', 'SAMSUNG'), ('MT', 'MOTOROLA')], max_length=100, verbose_name='Marca de Producto')),
                ('phone_model', models.CharField(max_length=100, validators=[phone.models.validate_product_data], verbose_name='Modelo de Producto')),
                ('phone_imei1', models.IntegerField(verbose_name='IMEI 1')),
                ('phone_imei2', models.IntegerField(verbose_name='IMEI 2')),
                ('phone_serial', models.CharField(default=0, max_length=100, unique=True, verbose_name='Serial')),
                ('phone_status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Reparado', 'Reparado'), ('Dañado', 'Dañado')], default='Nuevo', max_length=10, verbose_name='Estado')),
                ('phone_created', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creacion')),
                ('phone_number', models.IntegerField(verbose_name='Numero de Teléfono')),
                ('phone_quantity', models.IntegerField(default=1, validators=[phone.models.validate_product_quantity], verbose_name='Cantidad')),
                ('phone_buy', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de compra')),
            ],
            options={
                'verbose_name': 'Celular',
                'verbose_name_plural': 'Celulares',
                'db_table': 'Celular',
                'ordering': ['-phone_created'],
            },
        ),
    ]
