# Generated by Django 3.0.6 on 2022-05-18 20:49

from django.db import migrations, models
import warehouse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id_warehouse', models.IntegerField(primary_key=True, serialize=False, validators=[warehouse.models.validate_id_warehouse], verbose_name='ID Almacer')),
                ('warehouse_name', models.CharField(max_length=100, verbose_name='Nombre de Almacen')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'Almacen',
                'ordering': ['-id_warehouse'],
            },
        ),
    ]
