# Generated by Django 3.0.6 on 2022-05-18 20:49

import catastro_equipos.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id_product_status', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID Estado de Producto')),
                ('product_status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Reparado', 'Reparado'), ('Dañado', 'Dañado')], default='Nuevo', max_length=10, verbose_name='Estado del Equipo')),
            ],
            options={
                'verbose_name': 'Estado de Producto',
                'verbose_name_plural': 'Estado de Productos',
                'db_table': 'Estado_Producto',
                'ordering': ['id_product_status'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('product_name', models.CharField(max_length=100, validators=[catastro_equipos.models.validate_product_data], verbose_name='Marca producto')),
                ('type_product', models.CharField(choices=[('Notebook', 'Notebook'), ('Desktop', 'Desktop')], default='', max_length=20, verbose_name='Producto')),
                ('model_product', models.CharField(max_length=100, verbose_name='Modelo')),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Direccion Mac')),
                ('type_serial', models.CharField(blank=True, choices=[('NTBK', 'NTBK'), ('DKTP', 'DKTP'), ('N/A', 'N/A')], max_length=10, null=True, verbose_name='Tipo de Serial')),
                ('ram_pc', models.CharField(blank=True, choices=[('8', '8'), ('16', '16'), ('24', '24'), ('32', '32'), ('64', '64')], default='8', max_length=5, verbose_name='Ram instalada')),
                ('ram_pc_type', models.CharField(blank=True, choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4')], default='DD4', max_length=5, verbose_name='Tipo de Ram')),
                ('disk_pc', models.CharField(blank=True, choices=[('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB')], default='128 GB', max_length=50, verbose_name='Capacidad de Disco Duro')),
                ('disk_pc_type', models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SDD', 'SDD')], default='SDD', max_length=10, verbose_name='Tipo de Disco')),
                ('disk_pc_model', models.CharField(blank=True, choices=[('SATA 2.5', 'SATA 2.5'), ('NVME', 'NVME'), ('M2', 'M2')], default='NVME', max_length=10, verbose_name='Modelo de Disco')),
                ('processor', models.CharField(blank=True, choices=[('Intel', 'Intel'), ('AMD', 'AMD')], default='----', max_length=5, null=True, verbose_name='Procesador')),
                ('processor_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo de Procesador')),
                ('serial', models.CharField(default=0, max_length=100, unique=True, verbose_name='Serial')),
                ('active_code', models.CharField(default='BCN', max_length=20, unique=True, verbose_name='Codigo Activo')),
                ('created', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creacion')),
                ('product_quantity', models.IntegerField(default=1, validators=[catastro_equipos.models.validate_product_quantity], verbose_name='Cantidad')),
                ('buy_product', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de compra')),
                ('product_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro_equipos.ProductStatus', verbose_name='Estado de Producto')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse', verbose_name='Almacen')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['-created'],
            },
        ),
    ]
