# Generated by Django 4.0.1 on 2022-06-11 01:44

import catastro_equipos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro_equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('HP', 'HP'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('Macbook', 'Macbook'), ('MSI', 'MSI'), ('Lenovo', 'Lenovo'), ('Dell', 'Dell')], max_length=100, validators=[catastro_equipos.models.validate_product_data], verbose_name='Marca producto'),
        ),
    ]
