# Generated by Django 4.0.1 on 2022-06-14 16:34

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID Colaborador')),
                ('user_name', models.CharField(max_length=100, validators=[usuarios.models.validate_user_name], verbose_name='Nombre')),
                ('user_last_name', models.CharField(max_length=100, validators=[usuarios.models.validate_user_last_name], verbose_name='Apellido')),
                ('user_email', models.EmailField(default='@bcnschool.cl', max_length=100, validators=[usuarios.models.validate_email], verbose_name='Email')),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Numero de Telefono')),
                ('user_name_corp', models.CharField(max_length=100, unique=True, validators=[usuarios.models.validate_user_name_corp], verbose_name='Nombre corporativo')),
                ('user_corp', models.CharField(choices=[('Centro de Desarrollo y Formacion Continua SPA', 'Centro de Desarrollo y Formacion Continua SPA'), ('Escuela de Negocios BCN School SPA', 'Escuela de Negocios BCN School SPA'), ('Centro de Desarrollo NeoTec SPA', 'Centro de Desarrollo NeoTec SPA'), ('Sabantis SPA', 'Sabantis SPA')], default='Escuela de Negocios BCN School SPA', max_length=100, verbose_name='Empresa')),
                ('boss_user', models.CharField(default='', max_length=100, validators=[usuarios.models.validate_boss], verbose_name='Jefe Directo')),
                ('boss_user_dep', models.CharField(choices=[('Informatica', 'Informatica'), ('Recursos Humanos', 'Recursos Humanos'), ('Contabilidad', 'Contabilidad'), ('Logistica', 'Logistica'), ('Administracion', 'Administracion'), ('Consultoria', 'Consultoria'), ('Gerencia', 'Gerencia'), ('Produccion', 'Produccion'), ('Comercial', 'Comercial'), ('Diseño', 'Diseño')], default='', max_length=100, verbose_name='Departamento')),
                ('dp_boss', models.CharField(choices=[('Directora de Proyecto', 'Directora de Proyecto'), ('Jefe de Auditoria y Control Interno', 'Jefe de Auditoria y Control Interno'), ('Coordinador Académico', 'Coordinador Académico'), ('Director(a) de Proyecto', 'Director(a) de Proyecto'), ('Jefe de Coordinación Académica', 'Jefe de Coordinación Académica'), ('Key Account Manager', 'Key Account Manager'), ('Encargado de Logística y Control de Stock', 'Encargado de Logística y Control de Stock'), ('Lider Técnico', 'Lider Técnico'), ('Diseñador Multimedia y Jefe Técnico', 'Diseñador Multimedia y Jefe Técnico'), ('Office Manager - Comunicaciones Internas y Jefa de coordinación académica', 'Office Manager - Comunicaciones Internas y Jefa de coordinación académica'), ('Gerente General', 'Gerente General'), ('Jefe de Capacitación y Desarrollo Organizacional', 'Jefe de Capacitación y Desarrollo Organizacional'), ('Directora de Proyecto Junior', 'Directora de Proyecto Junior'), ('Gerente de Capacitación', 'Gerente de Capacitación'), ('Gerente Comercial', 'Gerente Comercial'), ('Subgerenta de Proyectos', 'Subgerenta de Proyectos'), ('Gerente de Marketing y Comunicaciones', 'Gerente de Marketing y Comunicaciones'), ('Subgerente TI', 'Subgerente TI'), ('Seguridad de la Información', 'Seguridad de la Información')], default='', max_length=100, verbose_name='Cargo de Jefatura')),
                ('user_status', models.CharField(choices=[('Activo', 'Activo'), ('Licencia', 'Licencia')], max_length=10, verbose_name='Estado')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Activo')),
                ('deparment_site', models.CharField(default='', max_length=100, verbose_name='Cargo Colaborador')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'Colaborador',
                'ordering': ['-user_name'],
            },
        ),
    ]
