# Generated by Django 4.0.1 on 2022-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.IntegerField(unique=True, verbose_name='Numero de Telefono'),
        ),
    ]
