# Generated by Django 4.0.1 on 2022-09-30 18:09

import datetime
from django.db import migrations, models
import infra.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infraestructure',
            fields=[
                ('id_ssh_user', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='id')),
                ('sub_area', models.CharField(max_length=100, verbose_name='Sub Area')),
                ('job_area', models.CharField(max_length=100, verbose_name='Cargo')),
                ('ssh_user', models.CharField(max_length=255, unique=True, validators=[infra.models.validate_user_name], verbose_name='Usuario')),
                ('ssh_key', models.CharField(max_length=100, unique=True, validators=[infra.models.validate_user_ssh], verbose_name='Nombre de llave ssh')),
                ('ssh_password', models.CharField(max_length=100, unique=True, validators=[infra.models.validate_password], verbose_name='Contraseña')),
                ('created', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Creación')),
                ('active_ssh_user', models.BooleanField(default=True, verbose_name='Usuario Activo')),
            ],
            options={
                'verbose_name': 'Listado de Cuenta',
                'verbose_name_plural': 'Listado de Cuentas',
                'db_table': 'Listado',
                'ordering': ['-id_ssh_user'],
            },
        ),
    ]
